### ISSUE TITLE
Support for Campaign Monitor API

### ISSUE THREAD

**Issue by meleksomai** [anymail/django-anymail#107]
Hi all,

I was wondering whether it is planned to add support to Campaign Monitor transactional API to Anymail. 

Campaign Monitor offers an API including a Python wrapper http://campaignmonitor.github.io/createsend-python/. Part of the API is to provide transactional services: https://www.campaignmonitor.com/api/transactional/ which should be compatible with Anymail functionalities.

Is it possible? If so, how to proceed? 

Thank you!

**Comment by medmunds** [comment]
Campaign Monitor's transactional sending looks like a good match for Anymail.

If anyone else would like to see this, please vote for it with GitHub's [thumbs-up reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/). And add a comment if you'd need to use OAuth rather than API keys...

Campaign Monitor offers [two kinds](https://www.campaignmonitor.com/api/getting-started/#authentication) of API auth: API keys would be straightforward to use with Anymail. OAuth would be more complicated (because Anymail doesn't have any way to store and update access tokens). If anyone wanting Campaign Monitor support in Anymail has a need for OAuth, it would be really helpful to understand that use case—please add a comment.

@protactinium if you'd like to take a shot at an integration, the [adding ESPs](https://github.com/anymail/django-anymail/blob/master/ADDING_ESPS.md) doc is where to start. I'm happy to answer questions or help on a work-in-progress pull request.

It looks like Campaign Monitor's "[smart email](https://www.campaignmonitor.com/api/transactional/#send-smart-email)" maps to Anymail's template/merge_data send, and their "[classic email](https://www.campaignmonitor.com/api/transactional/#send-classic-email)" would be used for normal sends.

Campaign Monitor's [webhooks](https://www.campaignmonitor.com/api/webhooks/#currently-available-webhooks) don't seem to include status tracking for sent messages, and they don't offer inbound handling, so the Anymail integration would just be an EmailBackend for sending.

Their Python package [seems to be a thin wrapper](https://github.com/campaignmonitor/createsend-python/blob/v5.0.0/lib/createsend/transactional.py#L31-L66) over the HTTP API calls, and I'm not sure it adds much value. It might be easier to just use Anymail's RequestsBackend to post directly to their API endpoint. (Their wrapper helps a little with OAuth, if there's a need for that, but it doesn't provide a complete solution.)

**Comment by medmunds** [comment]
There doesn't seem to be much interest in Campaign Monitor in django-anymail, so I'm going to close this issue for now. 

Happy to re-open in the future if that changes. Particularly if anyone wants collaborate on the implementation (and can get a Campaign Monitor test account for development).
