### ISSUE TITLE
Support for runtime based username/password backend authentication (SendGrid).

### ISSUE THREAD

**Issue by avelis** [anymail/django-anymail#12]
There are scenarios where one might need to reference at runtime credentials in to send to the ESP. Currently, it references a settings file key value pair. it would be nice to provide an alternative set that can be passed in at runtime.

**Comment by medmunds** [comment]
@avelis could you give a little more detail of your scenario?

There are a couple of ways Anymail could offer this:

1. As a *per-message* override, probably in the `esp_extra` dict. (Similar to how it handles [overriding Mailgun's sender_domain](https://anymail.readthedocs.org/en/latest/esps/mailgun/#email-sender-domain).) Something like:

    ```python
    message = EmailMessage(...)
    message.esp_extra = {"username": "OtherApiUser", "password": "..."}  # or "api_key": "..."
    message.send()
    ```

2. As a *connection-specific override,* which would apply to all emails sent using that connection:

    ```python
    message1 = EmailMessage(...)
    message2 = EmailMessage(...)
    connection = get_connection('anymail.backends.sendgrid.SendGridBackend',
                                username="OtherApiUser", password="...")  # or api_key="..."
    connection.send_messages([message1, message2])
    ```

The first approach is probably easier to explain and use. The second approach is (I think) more in keeping with the spirit of Django email backend connections, and is more likely to be portable to other ESPs and API bindings. (Which is why it would help to understand if this is a SendGrid-specific scenario or more generally applicable.)

**Comment by avelis** [comment]
@medmunds Good Question! I customized a solution almost exactly like Option 2.

I basically subclassed django-anymail's `SendGridBackend` as such:

```python
class SendGridDynamicAuthenticationBackend(SendGridBackend):

    def __init__(self, **kwargs):
        """Init options from Django settings"""
        # Auth requires *either* SENDGRID_API_KEY or SENDGRID_USERNAME+SENDGRID_PASSWORD
        self.api_key = get_anymail_setting('SENDGRID_API_KEY', default=None, allow_bare=True)
        self.username = get_anymail_setting('SENDGRID_USERNAME', default=None, allow_bare=True)
        self.password = get_anymail_setting('SENDGRID_PASSWORD', default=None, allow_bare=True)

        if 'auth_username' in kwargs and 'auth_password' in kwargs:
            # This is custom to our needs.
            self.api_key = None
            self.username = kwargs.get('auth_username', None)
            self.password = kwargs.get('auth_password', None)

        if self.api_key is None and self.username is None and self.password is None:
            raise ImproperlyConfigured(
                "You must set either SENDGRID_API_KEY or both SENDGRID_USERNAME and "
                "SENDGRID_PASSWORD in your Django ANYMAIL settings."
                "Optionally you can set 'auth_username' & 'auth_password' "
                "kwargs via the get_connection method."
            )

        # This is SendGrid's Web API v2 (because the Web API v3 doesn't support sending)
        api_url = get_anymail_setting("SENDGRID_API_URL", "https://api.sendgrid.com/api/")
        if not api_url.endswith("/"):
            api_url += "/"

        # This is a hack and not an ideal way to do this.
        AnymailRequestsBackend.__init__(self, api_url, **kwargs)
```

You will notice the hack comment I made. It helped me get around the configuration error. However, the code smell is what prompted me to ask for this feature.

As far as I know. SendGrid has subusers that can store their own credentials along with the parent account. Mandrill only has subaccount slugs but that might change as it moves into MailChimp as an addon.

I am unsure which is a better solution at the moment. I am open to either one.
