### ISSUE TITLE
Support of Built In Django Views and django.core.mail 

### ISSUE THREAD

**Issue by younes-alouani** [anymail/django-anymail#137]
I just discovered this application and I have some questions. 
Are all the Django Methods in [django.core.mail](https://docs.djangoproject.com/en/2.1/topics/email/) Supported ?
I'm using some built in views for authentication like [password reset view](https://github.com/django/django/blob/master/django/contrib/auth/views.py) that sends the mail. 
The content of the email in the template `registration/password_reset_email.html` is bellow  : 
```
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
```

Can I use this built in view or should I create a new view to support html content in the email ?
Will the link be clickable or the content will be plain text ?

**Comment by medmunds** [comment]
Yes, Anymail's EmailBackend implementations are all designed to work with the functions in django.core.email. (Django has a concept of "[custom email backends](https://docs.djangoproject.com/en/2.1/topics/email/#defining-a-custom-email-backend)," which allow you to swap out email providers without changing the rest of your code. Anymail implements a Django custom backend for each supported ESP.)

There's no need to create custom django.contrib.auth views to use Anymail (or any other custom email backend).

It sounds like you have a question about how to get Django's PasswordResetView to send html email, rather than plaintext. You might be looking for the [`html_email_template_name`](https://docs.djangoproject.com/en/2.1/topics/auth/default/#django.contrib.auth.views.PasswordResetView) option. But this doesn't really have anything to do with Anymail. Stack Overflow is probably a better place to get information about providing additional options to PasswordResetView.
