### ISSUE TITLE
Configuring credentials for amazon SES

### ISSUE THREAD

**Issue by anuj9196** [anymail/django-anymail#151]
This is not an error. 

I'm moving my application's email backend from Mandrill to SES. I like the feature **anymail** is providing and ease of changing provider without installing additional packages.

Meanwhile, I'm setting up SES and Mandrill both through this package so that switching providers will be a single line swapping.

But, I couldn't locate in the documentation, how to provide AWS credentials?
It is mentioned to configure Boto3 but Boto3 is also used by `django-storages` and AWS credentials there are provided by simply putting CLIENT_ID and SECRET in the settings file
```
AWS_ACCESS_KEY_ID = 'client_id'
AWS_SECRET_ACCESS_KEY = 'my_secret'
```

**Comment by medmunds** [comment]
There are a bunch of different ways to get AWS credentials into Boto3, some of which are much more suitable for production use than others... which is why [Anymail's SES docs](https://anymail.readthedocs.io/en/stable/esps/amazon_ses/#installation) defer to [Boto3's credential docs](https://boto3.readthedocs.io/en/stable/guide/configuration.html#configuring-credentials).

That said, if you just want to get something working quickly, you can use Anymail's [AMAZON_SES_CLIENT_PARAMS](https://anymail.readthedocs.io/en/stable/esps/amazon_ses/#std:setting-ANYMAIL_AMAZON_SES_CLIENT_PARAMS) setting:

```python
ANYMAIL = {
    "AMAZON_SES_CLIENT_PARAMS": {
        # Caution: checking secrets into settings.py is really insecure!
        "aws_access_key_id": "client_id",
        "aws_secret_access_key": "my_secret",
    },
}
```

Much safer alternatives for production use (all of these should also work with django-storages):
* Provide credentials in environment variables. Boto3 [automatically reads](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#environment-variables) `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` from the environment. Just omit any AWS credentials from your settings.py.
* If you're running on EC2, use an IAM Role for EC2 following Boto's recommended [best practice](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#best-practices-for-configuring-credentials). Again, just leave AWS credentials out of settings.py. You'll have to include the [IAM permissions Anymail needs](https://anymail.readthedocs.io/en/stable/esps/amazon_ses/#iam-permissions) in your IAM role.
* If you want to use a `~/.aws/credentials` [shared credentials file](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#shared-credentials-file), you can tell Anymail to use a specific `profile_name` with the [AMAZON_SES_SESSION_PARAMS](https://anymail.readthedocs.io/en/stable/esps/amazon_ses/#std:setting-ANYMAIL_AMAZON_SES_SESSION_PARAMS) setting.

**Comment by anuj9196** [comment]
Thanks, I setup environment variables for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and it works without specifying explicity in the settings.

But, it doesn't works for the `region`

I set up two environment variables 
```
REGION_NAME='us-east-1'            # as per anymail config
AWS_SES_REGION='us-east-1' 
```
But none is working and I had to provide region explicitly in the `ANYMAIL` config.
