### ISSUE TITLE
Consistent merge functionality

### ISSUE THREAD

**Issue by slinkymanbyday** [anymail/django-anymail#152]
I have recently moved from Mailgun to Sendgrid. As part of this I have noticed that the merge variables have a different format. 
For example, %recipient.name% for mailgun and something like -name- or {{name}} for sendgrid.

I feel like it would be helpful if anymail would have a consistent interface for this such that when changing mail provider, templates won't have to change.

I would imagine the implementation would be something like:
1) specify format string in settings similar to sendmail settings
2) If needed, rewrite the body/subject with the correct format

For example:
settings:
```"MERGE_FIELD_FORMAT": "-{}-"```
template:
```Hello -name-, how are you?```
merge data:
```
{
    'alice@example.com': {'name': "Alice"},
}
```
resulting body for sendgrid: no rewrite necessary
```Hello -name-, how are you?```
resulting body for mailgun: 
```Hello %recipient.name%, how are you?```

**Comment by medmunds** [comment]
Thanks, this is an interesting suggestion.

It's true that each ESP uses their own templating language, so ESP merge templates are inherently not portable between ESPs. (Sorry if this caught you by surprise. A portable alternative is to [use Django templates for email](https://anymail.readthedocs.io/en/stable/tips/django_templates/), and there are packages like [django-templated-mail](https://pypi.org/project/django-templated-mail/) that can help. The Anymail docs also discuss choosing [ESP vs Django email templates](https://anymail.readthedocs.io/en/stable/sending/templates/#esp-templates-vs-django-templates).)

As you've noticed, the ESP syntax for template merge fields varies widely. But there are other differences, too. Many ESPs templates also have:

* conditional if/else logic and looping over lists
* modifiers or filters you can apply to field values (e.g., `{{ name | title_case | default:"Customer" }}`)
* special built-in fields that aren't included in Anymail's merge_data (sender account info, recipient CRM data like date last emailed, which mailing lists they're on, etc.)
* special content references (e.g., `<%body%>` or `{{ unsubscribe_link }}`)

... but not every ESP supports all of these, and for the ones who do, the syntax for using them varies widely. I'm a little concerned that if Anymail translates *some* template features (like simple merge fields), developers might be surprised when it doesn't translate others. And I don't think it's realistic—or maybe even possible—for Anymail to translate or warn about every ESP template feature that might be used. 

One other concern is that many Anymail users work with ESP "stored templates" that are just referenced by `template_id` when sending. Anymail doesn't have access to the stored template definitions, so it wouldn't be able to help with those. (I believe Mailgun is the only ESP that *doesn't* offer stored templates.)

Given all that, I'm not sure how generally useful this feature would be. I'm not totally opposed to a PR, but it's not something I'm likely to work on myself.

-----

P.S., Because you're switching *to* SendGrid *legacy templates*, the current version of Anymail actually has you covered. If you want to use your on-the-fly Mailgun templates (`body='...%recipient.variable%...'`) with SendGrid, just set:

```python
ANYMAIL = {
    # ...
    'SENDGRID_MERGE_FORMAT': '%recipient.{}%'
}
```

(This only works with SendGrid's [*legacy templates*](https://anymail.readthedocs.io/en/stable/esps/sendgrid/#legacy-transactional-templates), and only covers simple merge fields. It won't help if you want to use their newer dynamic templates, other template features, or later switch to some other ESP. Which I'm guessing is why you opened this issue in the first place.)

**Comment by slinkymanbyday** [comment]
@medmunds 
Thanks for the detailed reply, really appreciate the effort put in to explain the issues involved with this. I didn't realise some ESPs allowed for such complex template logic. 
Given that even if this use case was to be taken into account, I agree it would cause more confusion than it would solve. Closing this, as given the issues with trying to implement something like this, I won't be submitting a PR.
