### ISSUE TITLE
SSLError: bad handshake: SysCallError(104, 'ECONNRESET')

### ISSUE THREAD

**Issue by cralston0** [anymail/django-anymail#16]
It looks like Mailgun has been dealing with an ongoing DDOS this morning, which caused a flurry of exceptions to be thrown by requests as used by django-anymail.

I'm honestly not sure if this is something django-anymail should catch and raise its own error, or if it should (immediately) retry the send, or leave the exception as-is and put the burden on the django application.

Slightly anonymized trace:

          File "my_code.py", line 274, in scheduled_emails
            email_msg.send()
          File "django/core/mail/message.py", line 303, in send
            return self.get_connection(fail_silently).send_messages([self])
          File "anymail/backends/base.py", line 82, in send_messages
            sent = self._send(message)
          File "anymail/backends/base_requests.py", line 56, in _send
            return super(AnymailRequestsBackend, self)._send(message)
          File "anymail/backends/base.py", line 110, in _send
            response = self.post_to_esp(payload, message)
          File "anymail/backends/base_requests.py", line 68, in post_to_esp
            response = self.session.request(**params)
          File "requests/sessions.py", line 468, in request
            resp = self.send(prep, **send_kwargs)
          File "requests/sessions.py", line 576, in send
            r = adapter.send(request, **kwargs)
          File "requests/adapters.py", line 447, in send
            raise SSLError(e, request=request)

**Comment by medmunds** [comment]
Hmm. I think Anymail *does* need to re-cast that requests exception as an AnymailRequestsAPIError (in anymail.backends.BaseRequests.post_to_esp). That's required for proper fail_silently handling.

Of course, that'll still leave you with a flurry of (different) exceptions, if you're not using fail_silently. 

There are several Django packages that maintain an email queue and robustly retry failed sends at a later time. Anymail should be compatible with most of them (any that let you change their email backend). 

* I personally use the old [Pinax django-mailer](https://github.com/pinax/django-mailer), which runs in Django's DB and works fine at my relatively-small scale. (Also, it seems to be getting maintained again -- yay!). 

* [Celery](http://www.celeryproject.org/) is popular for managing any sort of task queues in Django, and there are a bunch of Django email queues based on it.

* I'm sure there are others. (Including some interesting [explorations using Django channels](https://www.wordfugue.com/using-django-channels-email-sending-queue/).)

Queue-and-resend functionality isn't built into Anymail, because there are different approaches that satisfy different needs, and the other packages cover the tradeoffs well. (Also, Anymail doesn't itself maintain any state or run any async tasks.)

**Comment by cralston0** [comment]
Yep! I wouldn't propose a queueing system for Anymail -- edited the issue to clarify that.

This is already being fired from a Celery task where we catch most errors to turn them into a another delayed attempt. This one bubbled up though since it was new.
