### ISSUE TITLE
Doc links broken

### ISSUE THREAD

**Issue by karfau** [anymail/django-anymail#186]
On this page https://pypi.org/project/django-anymail/ are the following links:

> Full documentation: https://anymail.readthedocs.io/en/v7.1.0/
Package on PyPI: https://pypi.org/project/django-anymail/
Project on Github: https://github.com/anymail/django-anymail
Changelog: https://anymail.readthedocs.io/en/v7.1.0/changelog/

But the first and last one are broken
https://anymail.readthedocs.io/en/stable/ works though

**Comment by medmunds** [comment]
Sorry about that, and thanks for the report. Those links should work now.

(The problem was the release was tagged `v7.1`, but the [internal version number](https://github.com/anymail/django-anymail/blob/v7.1/anymail/_version.py#L1) was `7.1.0`. I've added a `v7.1.0` tag as an alias for the `v7.1` release.)
