### ISSUE TITLE
UnicodeEncodeError in SendGrid webhook

### ISSUE THREAD

**Issue by tcourtqtm** [anymail/django-anymail#187]
We are seeing this error occasionally from our SendGrid webhook:

```
UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 43: character maps to <undefined>
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "anymail/webhooks/base.py", line 109, in dispatch
    return super(AnymailBaseWebhookView, self).dispatch(request, *args, **kwargs)
  File "django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "anymail/webhooks/base.py", line 123, in post
    events = self.parse_events(request)
  File "anymail/webhooks/sendgrid.py", line 128, in parse_events
    return [self.esp_to_anymail_event(request)]
  File "anymail/webhooks/sendgrid.py", line 136, in esp_to_anymail_event
    message = self.message_from_sendgrid_parsed(esp_event)
  File "anymail/webhooks/sendgrid.py", line 192, in message_from_sendgrid_parsed
    attachments=attachments,
  File "anymail/inbound.py", line 289, in construct
    part.set_payload(text, charset=text_charset)
  File "email/message.py", line 315, in set_payload
    if not isinstance(charset, Charset):
  File "encodings/cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
```

* Anymail version: 7.1.0
* ESP: SendGrid
* Your ANYMAIL settings: all defaults except for secrets
* Versions of Django, requests, python: python 3.6.9, Django 3.0.6, requests 2.22

We've seen this for a few different characters. Here is an example of the text that tripped this exception:

```
Good morning,\n\nAs per your request below, I�ve done up a quote for you on our REDACTED.\nI�ve done up a one month quote as well as one for the full REDACTED.
```

**Comment by medmunds** [comment]
(Thanks for including the full stack trace.)

This is in the inbound message webhook. The problem seems to be that SendGrid is telling Anymail the inbound message body is encoded in UTF-8, but it's actually in some other character encoding. (And you can see the encoding is wrong from the Unicode replacement symbols in the snippet you posted: `I�ve` rather than `I’ve`.)

I'd need to see the complete webhook payload to know for certain where the problem's originating—in particular, the 'charsets' field. There are three possibilities:
* SendGrid has a history<sup>1</sup> of mis-handling character encodings elsewhere in their API. They might be giving the wrong charset for the inbound text body. 
* Older email apps are notoriously bad at handling non-ASCII characters. It's possible SendGrid received a broken message and just passed along bad data. (Do you know what app sent this message?)
* Anymail defaults to UTF-8 if SendGrid doesn't tell it what charset was used. If SendGrid is throwing up its hands on a broken message, Anymail might be making things worse with that default.

I *suspect* changing your SendGrid inbound parse to use "Send raw" would work around the problem. (See step 5 of SendGrid's [inbound parse setup](https://sendgrid.com/docs/for-developers/parsing-email/setting-up-the-inbound-parse-webhook/#pointing-to-a-hostname-and-url) instructions. Your Anymail settings won't change.) With that option, SendGrid hands Anymail the full, raw incoming message, and Anymail uses Python 3's excellent email parser, which can handle broken character set info.

---

<sup>1</sup> See "[wrong character set on text attachments](https://anymail.readthedocs.io/en/stable/esps/sendgrid/#limitations-and-quirks)" in Anymail's SendGrid "Quirks" docs.

**Comment by tcourtqtm** [comment]
Thanks for the quick reply!

I can't see the full message body, but I can see the parsed charsets field:

```
{
from: 'UTF-8', 
html: 'Windows-1252', 
subject: 'UTF-8', 
text: 'Windows-1252', 
to: 'UTF-8'
}
```

We're going to try your suggestion to turn on Send Raw.

**Comment by medmunds** [comment]
Interesting. So probably the message body is actually utf-8, but either the user's mail client called it Windows-1252, or it didn't specify so SendGrid guessed Windows-1252. (Which it turns out might be a reasonable guess, if I'm understanding the history of the charset declarations correctly.)

I don't suppose you can see the 'headers' field in the webhook payload? I'm curious about Content-Type (charset) and X-Mailer headers if they're in there.

I'm thinking that even if SendGrid (or another ESP) gets the charset wrong, Anymail should probably try to construct a valid message (probably with replacement symbols for the invalid chars) rather than raising an exception.

**Comment by tcourtqtm** [comment]
Since enabling the "Send raw" feature in SendGrid we haven't seen this error recur. :tada: Thank you so much for the suggestion!

I can see the webhook headers. The Content-Type is `multipart/form-data; boundary=xYzZY`. There is no X-Mailer header.

**Comment by medmunds** [comment]
OK, my mistake. On further investigation, this is in fact a bug in Anymail's inbound SendGrid webhook. If a message is received using an encoding other than utf-8, and you *aren't* using SendGrid's "send raw" option, Anymail can crash with a Unicode error. (Or could possibly leave incorrect characters in the inbound message body.)

SendGrid posts the message text and html in their original encodings (as received), and correctly specifies those encodings in the charsets field. However, Django decodes all post data in its DEFAULT_CHARSET (usually utf-8), and doesn't make it easy to read different fields using different encodings. (To be fair, browsers don't post forms using multiple charsets, so this isn't a situation that comes up often.)

I've found a fix, but I'm also going to change the docs to recommend using SendGrid's "send raw" option.
