### ISSUE TITLE
Inbound UnicodeEncodeError on Python 2.7

### ISSUE THREAD

**Issue by kika115** [anymail/django-anymail#197]
Reporting an error? It's helpful to know:

* Anymail version : 6. 
* ESP Postmark
* django 1.11.20 python 2.7.5 requests==2.24.0 
![image](https://user-images.githubusercontent.com/32838660/89422215-57882480-d735-11ea-8846-75e4dab9df82.png)

**Comment by kika115** [comment]
please check this bug , same bug is also in 7.2 version

**Comment by medmunds** [comment]
Thanks for the report.

This is a bug in Anymail's partial backport of the Python 3 email package. It only applies when running on Python 2.7. 

Please note that [Python 2 reached end of life](https://www.python.org/doc/sunset-python-2/) on January 1, 2020, and [Django 1.11 reached the end of its extended support period](https://www.djangoproject.com/download/#supported-versions) on April 1, 2020. Anymail [dropped support](https://anymail.readthedocs.io/en/v7.2/changelog/#deprecations) for both of those after last week's Anymail v7.2 release.

Because there seems to be a simple fix (and because Anymail just dropped those environments a week ago), I'm going to try to slip this into a v7.2.1 patch release. But going forward, the 7.2.x branch will only receive fixes for security issues and breaking changes in ESP APIs (and those only through July, 2021). As the Python project puts it, "You should upgrade to Python 3 as soon as you can."

**Comment by medmunds** [comment]
Fixed via #198 in Anymail v7.2.1.
