### ISSUE TITLE
Sparkpost unkown status for known statuses

### ISSUE THREAD

**Issue by slinkymanbyday** [anymail/django-anymail#206]
* Anymail version - 8.0
* ESP (Mailgun, SendGrid, etc.) - Sparkpost

Sparkpost has more statuses than what is accounted for in https://github.com/anymail/django-anymail/blob/main/anymail/webhooks/sparkpost.py#L56 

Specifically "initial_open" is not accounted for and gets reported as "unknown" instead of "open"

A full list of events can be found here: https://developers.sparkpost.com/api/webhooks/#header-webhook-event-types

**Comment by medmunds** [comment]
Thanks for the report. 

Anymail is designed to work across multiple ESPs, and so its tracking webhook `event_type` maps ESP events to a [limited list of normalized tracking events](https://anymail.readthedocs.io/en/stable/sending/tracking/#anymail.signals.AnymailTrackingEvent.event_type). That list includes event types that are supported by most ESPs; events that don't match one of the normalized types are mapped to "unknown". 

If your code needs to use those other "unknown" event types—and you don't mind locking it to a particular ESP—the raw webhook data is available in the [`event.esp_event`](https://anymail.readthedocs.io/en/stable/sending/tracking/#anymail.signals.AnymailTrackingEvent.esp_event) property in your signal receiver.

SparkPost is the only ESP* that offers an "initial_open" event that's only generated once per message, as well as a regular "open" that's generated on every open. I originally had mapped both of those into Anymail's normalized "opened" event. But SparkPost's webhook settings used to default to all events enabled, and this led to apparently duplicate Anymail "opened" events (because SparkPost generates *both* "initial_open" and "open" on a message's first actual open).

SparkPost has since redesigned their webhook configuration screen, defaulting all events disabled, and they've added several new events. I *think* it would be OK to map SparkPost "initial_open" to Anymail "opened" as long as we add some clear documentation explaining that enabling both "open" and "initial_open" will lead to duplicate events. We would need to treat that as a **breaking change** since it could impact people's existing deployments.

Also, probably the new SparkPost events "amp_click" and "amp_open"/"amp_initial_open" should map to Anymail's "clicked" and "opened" events.


<hr>

\* Postmark has a configuration option where you can receive open events *either* on every open or only on first open. But you can never get two events for the same actual open.

**Comment by slinkymanbyday** [comment]
Didn't realise about the 2 events on the one open. Agreed there would nee to be documentation and a major bump for something like that.

In my app I track the state of an email with the Anymail statuses. I only care if an email has been opened, not how many times, so it would be unnecessary for me to receive a webhook request on every subsequent open. So my plan was to just track the initial open (similar to how you say postmark does it). 

I'll change my SparkPost settings for now, however long term would prefer to not need the extra requests to the webhook.

**Comment by medmunds** [comment]
If you want to handle SparkPost's initial_open events with the current version of Anymail, you could examine the raw `event.esp_event`:

```python
if event.esp_event["msys"].get("track_event", {}).get("type") == "initial_open":
    do_something_for_opened_email(event.recipient)
```

(Even on event types Anymail treats as "unknown", it still tries to provide its other normalized fields like `event.recipient` if the data is available.)
