### ISSUE TITLE
requests.exceptions.InvalidHeader: Invalid return character or leading space in header: Authorization

### ISSUE THREAD

**Issue by instantrad** [anymail/django-anymail#208]
Reporting an error? It's helpful to know:

* Anymail version: django-anymail==8.1
* ESP (Mailgun, SendGrid, etc.): Sendgrid
* Your ANYMAIL settings (change secrets to "redacted")
* Versions of Django, requests, python: Python 3.7, Django 3
* Exact error message and/or stack trace
`  File "/Env/lib/python3.7/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/Env/lib/python3.7/site-packages/anymail/backends/base.py", line 94, in send_messages
    sent = self._send(message)
  File "/Env/lib/python3.7/site-packages/anymail/backends/base_requests.py", line 58, in _send
    return super()._send(message)
  File "/Env/lib/python3.7/site-packages/anymail/backends/base.py", line 124, in _send
    response = self.post_to_esp(payload, message)
  File "/Env/lib/python3.7/site-packages/anymail/backends/base_requests.py", line 79, in post_to_esp
    email_message=message, payload=payload) from err
anymail.backends.base_requests.AnymailRequestsAPIError: Error posting to https://api.sendgrid.com/v3/mail/send:
requests.exceptions.InvalidHeader: Invalid return character or leading space in header: Authorization`
* Any other relevant code and settings (e.g., for problems
  sending, your code that sends the message)
`headers': {'Authorization': 'Bearer u7xQRHYKOnfjY\r', 'Content-Type': 'application/json', 'Accept': 'application/json'}`

**Comment by instantrad** [comment]
This workaround fixed it on **sendgrid.py**

`http_headers['Authorization'] = 'Bearer %s' % backend.api_key.replace('\r','')`

**Comment by medmunds** [comment]
@instantrad your `SENDGRID_API_KEY` setting should not have a `\r` character in it in the first place. You should probably take a look at how it is being initialized in your settings.py file.

For example, are you perhaps loading secrets from a dotenv file? If so, it's possible the code that reads the dotenv file is incorrectly opening it in binary mode, rather than text mode. (In text mode, Python generally fixes up CR and NL line endings for you.) And if that's the case, you'll run into similar problems with other secrets in your settings.py.

Also, I don't quite understand the headers info you added. Is that copied from Anymail's DEBUG_API_REQUESTS output? It shows an Authorization header with a 13 character (plus `\r`) Bearer token, which is much too short to be a SendGrid API key. Are you maybe using your SendGrid account password in your settings where the API key belongs? (If it's your password you should reset it immediately, as it's now public on GitHub!)

**Comment by medmunds** [comment]
@instantrad since this is almost certainly a problem with your settings.py, not an Anymail issue, I'm going to close it. You can re-open if you have more info.
