### ISSUE TITLE
Slow Mailgun email deliveries.

### ISSUE THREAD

**Issue by corpulent** [anymail/django-anymail#210]
This is not exactly an error and more of a question.  I am using Mailgun and SendGrid,  with the same specs described below.  SendGrid deliveries are instant,  Mailgun many times takes up to 2 minutes if not more.  I opened a ticket with Mailgun and this is what they said.

```
I was able to find the message and its details which show our delivery latency of ~1min 15secs.

Anything lower than 5 is considered optimal and lower than 15 is nominal. If you have a message-id showing higher than 
that we can look into please let us know, though we cannot directly address such issues, only confirm latency was a factor.

As a suggestion, you seem to be using SMTP which carries a lot of legacy transactional overhead, thus increased sending 
latency. If possible convert over to using the Sending API as it's our core product. 
https://documentation.mailgun.com/en/latest/user_manual.html#sending-via-api
If normal API speeds aren't expedient enough or mission-critical delivery backed by an SLA is required consider our Rapid
 Fire Email support (requires API usage) https://www.mailgun.com/rapid-fire-email/

If you're seeing delays outside of what we cannot account for they are usually a result of deliverability by the recipient's 
MTA infrastructure and policies. You will need to engage the recipient admin to find solutions. A common problem sender
 see is called "ESP Throttling" where recipients defer messages for hours/days even though we only take seconds to deliver
 a message. We have a write up about this here: https://www.mailgun.com/blog/yahoo-aol-throttling-mailgun-festivus-
airing-grievances-part-two/** **though this doesn't seem to be affecting you in the provided example.
```

Looking over the django-anymail code it seems it is using their latest API.  But my payloads to Mailgun still show `SMPT`.

* Anymail version 
```
django-anymail[mailgun]==8.1
django-anymail[sendgrid]==8.1
```

* ESP (Mailgun, SendGrid, etc.)
Mailgun and SendGrid

* Your ANYMAIL settings (change secrets to "redacted")
```
ANYMAIL = {
    # (exact settings here depend on your ESP...)
    #"MAILGUN_API_KEY": os.environ.get("MAILGUN_API_KEY", ""),
    #"MAILGUN_SENDER_DOMAIN": os.environ.get("MAILGUN_SENDER_DOMAIN", ""),  # your Mailgun domain, if needed
    "SENDGRID_API_KEY": os.environ.get("SENDGRID_API_KEY", "")
}
#EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
EMAIL_BACKEND = "anymail.backends.sendgrid.EmailBackend"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "")  # if you don't already have this in settings
SERVER_EMAIL = os.environ.get("SERVER_EMAIL", "")  # ditto (default from-email for Django errors)
```

* Versions of Django, requests, python
Python 3.7
```
requests==2.23.0
django==3.0.7
```

* Exact error message and/or stack trace
* Any other relevant code and settings (e.g., for problems
  sending, your code that sends the message)

**Comment by medmunds** [comment]
Huh. So, Anymail *definitely* uses Mailgun's HTTP Sending API, *not* SMTP.

I suspect the support rep is misinterpreting the Mailgun logs, which seem to contain `"envelope": {
... "transport": "smtp" ... }` for messages sent through their Sending API. You can verify this yourself by using their [API curl example](https://documentation.mailgun.com/en/latest/user_manual.html#sending-via-api) and checking the logs in their dashboard—that's what I just did. (I'm guessing transport:smtp indicates messages delivered through the standard email infrastructure, as opposed to SMS or IM or other delivery mechanisms Mailgun might have thought about supporting at some point.)

(There *are* some ways your code could be overriding Django's EMAIL_BACKEND setting for individual messages, and that *could* be used to send through Django's SMTP EmailBackend and Mailgun's SMTP API rather than Anymail and Mailgun's HTTP API. But you would know if you written code that does that.)

> If you have a message-id showing higher than that we can look into ...

You can grab the Mailgun message-id from [`message.anymail_status.message_id`](https://anymail.readthedocs.io/en/stable/sending/anymail_additions/#anymail.message.AnymailStatus.message_id) right after sending, if that helps.

I don't have any answers for you, but a few other things you might look at:

* How are you determining the delivery delay? If possible, look at the dashboard API logs and compare the "accepted" time to the "delivered" time for each message. Accepted is when Anymail handed off to Mailgun; delivered is when Mailgun successfully passed it along to the receiving server. It can take some time after that to actually appear in a user's inbox. If the delay is between accepted and delivered, that's clearly Mailgun's issue. If it's between delivered and actual inbox arrival, the delay is at the receiving end, and may or may not be something you can affect.

* Postmark publishes their [time to inbox](https://status.postmarkapp.com/) stats for major ISPs, updated every 5 minutes. This won't necessarily parallel sends from Mailgun or SendGrid, but it's a source of data that might be helpful. (E.g., at the moment, email sent by Postmark to @me.com addresses is averaging well over a minute to hit the inbox, vs. under 10 seconds for the other ISPs.) 

* For the messages that are delayed, can you identify anything in common about them? E.g., are they all sent to addresses at one domain? I've heard of cases where a corporate email scanner apparently gets backlogged, or thinks a particular sending IP needs extra scrutiny and takes longer to scan those messages. (And this could vary with which ESP you're using as well as the receiving email scanner's rules and load.)

* Do you have SPF, DKIM, and DMARC set up properly? (And does your SPF cover both Mailgun and SendGrid, since you're switching between them?) Your sending reputation can affect how much scrutiny (and throttling) the ISPs apply to mail you send. Without SPF+DKIM+DMARC, your reputation depends a lot more on the IP address you're sending from—and whatever other ESP clients you're sharing that IP with. (The ISPs don't divulge their exact practices, but there seems to be belief that sender domain reputation has replaced IP reputation for verifiable sender domains.)

* Related: are you a new customer at Mailgun? If so, they may have placed you in a "high risk" sending pool that lumps you in with other new customers until you've proven yourself. And depending on what those other customers are doing, Mailgun may be throttling sends to particular destinations in your pool. (All responsible ESPs do this. It'll show up as a delay between accepted and delivered in the logs. Of course, if that's what's going on, the support rep really should have mentioned it.) (BTW, *SendGrid* is notorious for—without notice—moving established, *paying* customers on its lower price plans into throttled high risk sending pools, and then promoting higher priced dedicated IP plans when messages are delayed.)

**Comment by medmunds** [comment]
@corpulent I'm going to close this issue, since it doesn't seem to be directly related to Anymail. Feel free to update and re-open if you get more information.

**Comment by corpulent** [comment]
@medmunds Sounds good.  It's not related to Anymail.  I am still investigating.  SPF, DKIM, and DMARC is all set up properly. It's most likely related to being a new customer of Mailgun.  I just can't find this info anywhere in their docs, so I will reach out to their customer support again.

Thanks for your thorough response!  I saved it to my notes.
