### ISSUE TITLE
Postmark TLS config

### ISSUE THREAD

**Issue by adnathanail** [anymail/django-anymail#225]
Postmark have announced they are dropping support for TSLv1 and removing support for RC4 ciphers
https://postmarkapp.com/updates/upcoming-tls-configuration-changes-for-api-users-action-may-be-required

Is this something that will affect the latest version of anymail?

Thanks!

**Comment by medmunds** [comment]
Short answer: this doesn't directly affect *any* version of Anymail, because Anymail relies on other packages to secure its communications with ESPs. If you are using Anymail with ancient versions of some other packages or on an outdated OS, it could possibly affect you.

Long answer: There's no code in Anymail specific to TLS versions. Anymail uses the [Python Requests](https://requests.readthedocs.io/en/stable/) package for communication with most ESPs, including Postmark. Under the hood, Requests uses the [urllib3](https://urllib3.readthedocs.io/en/stable/) package to make and secure the connection. I believe urllib3 uses the best version of TLS and ciphers available to your Python installation (and supported by the remote server). Any reasonably up-to-date system should have support for TLS 1.2 (and probably 1.3) at this point.

If you want to be certain, you can:

1. Check your Python installation via HowsMySSL.com (as suggested in [this Python Software Foundation post](https://pyfound.blogspot.com/2017/01/time-to-upgrade-your-python-tls-v12.html)):
    ```sh
    python3 -c "import requests; print(requests.get('https://www.howsmyssl.com/a/check').json()['tls_version'])"
    python3 -c "import requests; print(requests.get('https://www.howsmyssl.com/a/check').json()['insecure_cipher_suites'])"
    ```
   If the TLS version is less than 1.2, or any insecure cipher suites are in use, you need to upgrade Python and/or related packages.

2. Point Anymail at Postmark's temporary test/validation API endpoint, as suggested in their announcement. In your settings.py:
    ```python
    ANYMAIL = {
        "POSTMARK_API_URL": "https://api-ssl-temp.postmarkapp.com/",
        # ... other settings as before
    }
    ```
   And then send some email through your app. If it succeeds, you're definitely good to go. (Be sure to remove the POSTMARK_API_URL override when you're done.)

**Comment by adnathanail** [comment]
@medmunds that's incredibly helpful - thanks!

**Comment by medmunds** [comment]
[Mailgun is also dropping support for old TLS versions](https://www.mailgun.com/blog/tls-version-1-0-and-1-1-deprecation/), and the [answer above](#issuecomment-782920347) applies equally to them. 

To validate using Mailgun's test endpoint, you would temporarily set `"MAILGUN_API_URL": "https://api-test.mailgun.net/v3"` in your ANYMAIL settings.
