### ISSUE TITLE
MultiValueDictKeyError in inbound email because of mismatch in count and actual files

### ISSUE THREAD

**Issue by erikdrums** [anymail/django-anymail#272]
We are using Anymail 8.5, Django 3.2.12, Python 3.9.1 and have for a while been getting MultiValueDictKeyError ( in request.FILES[att_id] ) on some inbound Mailgun emails here https://github.com/anymail/django-anymail/blob/main/anymail/webhooks/mailgun.py#L406 

```
attachments = [
    AnymailInboundMessage.construct_attachment_from_uploaded_file(
        request.FILES[att_id], content_id=att_cids.get(att_id, None))
    for att_id in att_ids
]
``` 
It seems request.POST[”attachment-count”] doesn’t match number of files in request.FILES and attachment-count doesn’t match number of attachment-%d. 
I don’t know if this is Mailgun removing some files or why, but maybe we could make Anymail handle it. We are seeing quite a few inbound mails not coming through at all because of this mismatch in counts. After all it would be better to have them come through with missing attachments rather than not coming at all, perhaps with an added flag of missing attachement so each implementation can handle potentially missing attachments.

Below is an example of the relevant section of the request.POST content. Attachment-count (5), content-id-map (3) and actual attachment keys (2) don’t match. 
```
{
    'attachment-1': ['”BINARY_CONTENT”], 
    'attachment-2': [”BINARY_CONTENT”], 
    'attachment-count': ['5'], 
    'content-id-map': ['{"":"attachment-1","":"attachment-2","":"attachment-3"}'], 
}
```

**Comment by medmunds** [comment]
Weird. That `content-id-map` is also very broken. It might be helpful to see `request.FILES.keys()` alongside the `request.POST` content.

Just to double check, does your Django settings.py have FILE_UPLOAD_HANDLERS or MIDDLEWARE that could be affecting request.FILES? Maybe something that filters uploaded files? (It's unlikely, since I can't imagine it also altering the content-id-map, but I'd like to be sure.)

My best guess is these are malformed messages that are confusing Mailgun's inbound parser. Are there any clues in the other POST fields that might help narrow down the source? E.g., is it always senders from a particular domain? Do the subjects seem spammy? (A lot of spam is malformed.) Do the message-headers identify a particular mail client app?

You could probably avoid the problem by switching the webhook to "raw MIME": in your Mailgun routing config, just change `forward(".../anymail/mailgun/inbound/")` to `forward(".../anymail/mailgun/inbound_mime/")`. That moves the inbound parsing—including attachment handling—from Mailgun to Anymail via Python's standard email package.

> maybe we could make Anymail handle it

Yes, definitely, if Mailgun is generating this data, Anymail should handle it. I'd like to understand a little more about why it's happening—and ideally have a reproducible test case—first.

But here's the quick fix to just ignore the missing attachments:

```patch
  attachments = [
      AnymailInboundMessage.construct_attachment_from_uploaded_file(
          request.FILES[att_id], content_id=att_cids.get(att_id, None))
      for att_id in att_ids
+     if att_id in FILES
  ]
```

I'll have to think a little about how to flag them as missing instead. Maybe something like empty attachments with the content-type "application/x.missing"?

**Comment by erikdrums** [comment]
Thanks for looking at this!
Nothing in FILE_UPLOAD_HANDLERS or MIDDLEWARE that should affect it. 
Should have posted the output of request.FILES.keys(). 
```
dict_keys(['attachment-4', 'attachment-5'])
...
exception raise:
MultiValueDictKeyError('attachment-1')
```
Seems strange request.FILES would have 4 and 5 but not the preceding.
Thanks for the fix also, I have something similar just with some logging. 
If switching to ```forward(".../anymail/mailgun/inbound_mime/")``` fixes it, we can just leave it here

**Comment by medmunds** [comment]
Thanks for the extra info! I think I know what's going on.

I suspect the message has some unusual attachment filenames and/or content-ids, which are running into some security features (or possibly bugs) in Django's multipart/form-data handling:

1. If an attachment has an empty filename, Django doesn't treat it as a file. It ends up as a request.POST field. (See the content-disposition logic in [`django.http.parse_boundary_stream()`](https://github.com/django/django/blob/3.2.12/django/http/multipartparser.py#L210-L217).)
2. If an attachment's filename is `.`, `..`, or anything ending in `/` or `\`, Django silently drops the field. It won't appear in either request.POST or request.FILES. (See [`django.http.MultiPartParser.parse()`](https://github.com/django/django/blob/3.2.12/django/http/multipartparser.py#L210-L217) when `sanitize_file_name()` sanitizes away the entire name. This might be considered a Django bug—Django should probably generate a random filename rather than dropping the field—but at least some of this logic seems to be deliberate for security.)

So in the case you showed, attachment-1 and attachment-2 probably had empty filenames and got placed in request.POST; attachment-3 probably had a filename like "image/" or "." which sanitized to nothing, so got dropped entirely; and attachment-4 and attachment-5 had normal filenames and landed in request.FILES as expected.

I simulated a Mailgun inbound webhook call with those attachment filenames and was able to replicate the error you saw. (Though I haven't yet tried to send a real email into Mailgun to reproduce it, and I don't know exactly how to cause that broken content-id-map field.)

Anymail's MailgunInboundWebhookView needs fixes to handle these cases:
* If an attachment isn't found in request.FILES, check in request.POST too. [Item 1 above.]
* If the attachment isn't in either place, ignore it or substitute a "filtered attachment" placeholder. [Item 2 above. Unfortunately, I don't see any easy way to recover an attachment that Django skipped over.]
* If the content-id-map contains empty cids, replace them with unique "missing cid" placeholders. [This tries to ensure inline attachments end up inline, despite the broken map.]

Switching to the inbound_mime webhook will avoid all of this, and you'll get all of the message's original attachments. (With their original filenames, so be careful! They might be "/root/" or "../../.." or similar.)

**Comment by medmunds** [comment]
Looks like this would also affect SendGrid inbound. (And although test_sendgrid_inbound specifically tries to test an attachment with an empty filename, Django's TestClient subverts it by overriding the empty filename.)

**Comment by erikdrums** [comment]
Sound plausible. I can also test it and see if I can brake content-id-map. 
I agree that there is no good solution. But a least it seems better to actually receive the message and somehow flag the missing attachments.
I would love to help in any way, but am on holiday til the 19th. 
Let me know if there is anything I can do

**Comment by medmunds** [comment]
Thanks, appreciate the help.

I'm finishing up a fix, and will open a PR sometime next week. Would be helpful to verify it fixes the real problem (and not just my simulations of it).

But the Anymail fix is really just a workaround to avoid the errors. It can't recover the information lost in Django's multipart/form-data handling. There are Django issues open for both the cases above: https://code.djangoproject.com/ticket/15879 and https://code.djangoproject.com/ticket/18150. (Both over 10 years old.) Fixing this properly would require fixing those Django issues.

If you're able to figure out anything about the problem messages, that might be helpful in moving the Django issues forward. If, say, it turned out that messages from Yahoo Mail (or Outlook 2016 or whatever) frequently have inline images without filenames, and Mailgun is posting those as multipart/form-data fields with empty filenames, that's a legitimate use case that would argue for fixing Django's 15879.

**Comment by erikdrums** [comment]
I have been trying to gather useful mail-data. As far as I can tell it doesn't originate from a specific mail client. 
I think the following is an example - where Content-Disposition is inline and doesn't have a filename for what ever reason:
```
Content-Type: image/jpeg
Content-Transfer-Encoding: base64
Content-Disposition: inline 
```
I have to go back a few steps to get more useful data. I will be back.

**Comment by medmunds** [comment]
> where Content-Disposition is inline and doesn't have a filename

Perfect, thanks! I'm able to reproduce the empty filename behavior by sending a message with inline attachments that have no filename param (or that have `filename=""`). (Btw, these are perfectly valid emails—inline attachments aren't required to have filenames.)

But I haven't been able to reproduce the broken content-id-map that has empty, duplicate keys:

```python
    'content-id-map': ['{"":"attachment-1","":"attachment-2","":"attachment-3"}'], 
```

I can't find a way to get `""` as the keys in that JSON blob: when I send inline attachments with empty Content-ID fields, those don't even appear in the content-id-map. (And I can't get the same key to appear multiple times in the map, even with non-empty Content-IDs.)

Is it possible something (logging software?) filtered the content IDs before you captured them? Maybe because it mistook them for email addresses? (The specs call for using Message-IDs as Content-IDs, and a typical Message-ID is something like `165162769783.76258@local.example.com`. If that got stripped away before you captured it, it would explain why I can't find a way to recreate the behavior.)

**Comment by erikdrums** [comment]
Strange. The output is simply from request.POST. I can't see that anything should filter it. We use Sentry but this was captured and sent to my mail without throwing an error. I can't see anything else would interfere.   

I went back to using ```anymail/mailgun/inbound``` to get more errors. I can get the full mime when it occurs. I will post it as soon as I get one.

**Comment by medmunds** [comment]
Huh. Some other possibilities on that content-id-map:
* Maybe Mailgun is running different versions of its inbound email gateway in different regions (or on different inbound servers), and the version I hit handles empty content ids differently from the one you're using. (I was testing on Mailgun's US infrastructure.)
* Maybe the content ids aren't empty strings at all, but are composed entirely of non-printing characters (control characters, Unicode zero width spaces, joiners, bidi marks, etc.). I can't imagine this happening accidentally, but maybe in malicious content.
* Or… ??? It's definitely weird.

**Comment by medmunds** [comment]
OK, I've opened a PR #275 with a workaround that just ignores the missing attachments. (It also should handle the broken Mailgun content-id-map, though I still can't reproduce that.) I'll merge it later this week.

I'd originally written a bunch of code to try to fill in placeholders for the missing attachments, with a special *application/x.anymail-missing* content type. But it was adding a lot of complexity and was hard to explain in the docs. Also, I felt like Anymail users who might consider updating their code to deal with those placeholders would probably just prefer to switch to the raw MIME option (and avoid the problem altogether). So instead I've updated the Mailgun and SendGrid inbound docs to recommend using raw MIME. (The non-raw-MIME handling is still supported for now, but I think it should eventually be deprecated and removed.)

By the way, the dropped attachments issue probably became more common about a year ago, with Django patch releases 3.1.8, 3.0.14, and 2.2.20 to address CVE-2021-28658. Those added to the filename patterns that Django would simply drop during multipart/form-data sanitization.

**Comment by erikdrums** [comment]
Great! thanks for a great library and all your work!
I agree with deprecating the non-raw-MIME solution. It seems it is better for Anymail to have more control. We very little knowledge I would assume it makes it easier normalizing inbound mails from the different client also.

Don't hesitate to reach out if you need help with anything!

**Comment by erikdrums** [comment]
If you are interested I can send you an error email in mime. I have to protect the content so it would have to be to you personally

**Comment by medmunds** [comment]
Oh, yes, it would be helpful to have look at that, thanks. I'm [my GitHub username] AT gmail.com.

**Comment by medmunds** [comment]
@erikdrums thanks for the example failing message.

The problem was indeed an attachment without a filename—in this case, a forwarded message attachment:

```eml
Content-Type: message/rfc822
Content-Disposition: attachment;
    creation-date="Thu, 01 May 2022 01:01:01 GMT";
    modification-date="Thu, 01 May 2022 01:01:01 GMT"

[…forwarded message content…]
```

Mailgun's fully-parsed inbound data represents that as a multipart/form-data attachment field with no filename, and Django (mis-)handles that like it does an empty filename: the field ends up in request.POST rather than request.FILES, and the Content-Type gets lost. (Details in my [earlier comment](#issuecomment-1090816865).)

Using Mailgun's (and SendGrid's) raw MIME inbound option still seems like the best way to solve this. 

(I've realized another solution would be for Anymail to bypass Django's broken multipart/form-data parsing. The Mailgun and SendGrid inbound webhooks could instead run the raw request.body through the working multipart parser from the Python standard email package. I'm not currently planning on implementing this, but if anyone runs into problems with raw MIME we could consider it.)
