### ISSUE TITLE
Mailersend ESP support

### ISSUE THREAD

**Issue by anugrahsoft** [anymail/django-anymail#298]
Hi,

We really appreciate guys if you could integrate mailersend ESP (https://mailersend.com), and Sendpulse ESP (https://sendpulse.com/)

it's a reaaaaly serious player in the ESP space, with 12,000 to 15,000 emails/month Send for free

Thank you

**Comment by medmunds** [comment]
MailerSend seems like a good fit for Anymail: it has a [transactional send API](https://developers.mailersend.com/api/v1/email.html), supports templates, merge-variables, and batch-sending. It has [tracking webhooks](https://www.mailersend.com/help/webhooks) and [inbound support](https://www.mailersend.com/help/inbound-route). And it has a free allowance sufficient for development and ongoing testing.

One problem is that MailerSend's free plan doesn't include inbound routing. It's nearly impossible to get inbound support correct without being able to test it. If you're associated with MailerSend and could provide a development account for Anymail (with inbound support), that would be enormously helpful.

If anyone wants to work on a MailerSend integration, a PR would be welcome. Otherwise, I'll add it to my list (and drop a note here if/when I start working on it), but there's a bunch of other Anymail maintenance work in the queue ahead of it.

[Please open a separate issue for SendPulse. Or better yet, a [Discussion](https://github.com/anymail/django-anymail/discussions). Keeping a single topic per issue helps organize the conversation.]

**Comment by Agathe-Brusset** [comment]
Hello @medmunds , I am Agathe Brusset, MailerSend's product manager, and I can get you a test account to create the integration, just send me an email (agathe at mailersend dot com) and I'll make sure you have everything you need!

Thanks for considering adding MailerSend to Anymail, we're looking forward to it!

**Comment by medmunds** [comment]
@Agathe-Brusset thanks for getting us set up with a MailerSend test account. I'm bumping this up to the top of my Anymail queue (just need to finish the Amazon SES v2 updates first).

**Comment by anugrahsoft** [comment]
That is the great news ever this year :)

Can't wait to see Mailersend integrated into anymail

Thank you guys.

**Comment by medmunds** [comment]
MailerSend support is available in Anymail 9.1, just released.
