### ISSUE TITLE
SendGrid transactional emails with templates are received as plain text.

### ISSUE THREAD

**Issue by Ivaylo-Bachvarov** [anymail/django-anymail#32]
I decided to use SendGrid because of the nice WUSIWUG email editor that they have. I made all of my email templates nice and beautiful there. I copied the code from the django-anymail documentation and everythink is working just fine. The emails are interpolated correctly but there is no html at all. They are just plain text.

Here is the code that I have:
```python
def send_mail(self, recipient, template_id, context, **kwargs):
    message = EmailMessage(
        subject=" ",
        body=" ",
        from_email=settings.DJANGO_DEFAULT_FROM_EMAIL,
        to=[recipient]
    )

    message.template_id = template_id  # SendGrid id
    message.merge_data = {
        recipient: context,
    }

    message.send()

``` 

I tried many email clients but there is no html email at all. Just a plain text :cry:

**Comment by medmunds** [comment]
Yikes! Spent a while trying to figure this out. The short answer is, you'll need to add an HTML body to your EmailMessage, because otherwise SendGrid assumes you don't want HTML:

```python
    # ...
    message.attach_alternative(" ", "text/html")  # single space; not an empty string
    message.send()
```

(But keep the plaintext `body=" "` too, or SendGrid will decide you don't want the text version. sigh.)

The explanation is [buried in SendGrid's template docs](https://sendgrid.com/docs/API_Reference/Web_API_v3/Transactional_Templates/smtpapi.html#-Text-or-HTML-Templates): "If the text property is present, but not html, then the resulting email will only contain the text version of the template, not the HTML version."

Also, as you've discovered, you can't use truly empty strings (`""`) for SendGrid's subject or body, or you get API errors about those fields being missing. Very annoying if you've fully specified the subject and body in your template and don't care to add to them. The single space seems like a reasonable workaround.

At a minimum, I'll update the SendGrid-specific template docs to reflect this. I'm wondering if maybe Anymail should force both text and html bodies (and the subject) to `" "` if they're missing or empty, at least when using a template_id.

**Comment by medmunds** [comment]
(Oh, and even more confusingly, if you don't include an HTML body, SendGrid ignores your HTML template as documented, but then _they generate an HTML part from your plaintext template_ and include that in the message. Couldn't figure out why View Original on the received messages showed there _was_ an HTML part, just not the HTML from my template!)

**Comment by Ivaylo-Bachvarov** [comment]
Only EmailMultiAlternatives has attach_alternative method :smile: 

I see that the v3 API is released and is much simpler. What about migrating to v3 API?

**Comment by medmunds** [comment]
You should be able to substitute an EmailMultiAlternatives anywhere you're using EmailMessage.

It looks like SendGrid's v3 API has the same limitation: that link I posted is actually to their v3 docs. (Despite that, I'd still really like to switch to it, but there's a [backwards compatibility issue](https://github.com/anymail/django-anymail/issues/28#issuecomment-237396112) around auth support.)
