### ISSUE TITLE
Isn't clear how to use the testing backend

### ISSUE THREAD

**Issue by martmatwarne** [anymail/django-anymail#36]
So I've been using anymail for a while to send emails but now I've started work on tracking emails and I'm running into some issues around testing. The issue at the moment is that I've got lots of places in the code that read:

```
msg = self.generate_email()
msg.send()

email_sent = self.create_sent_object(email_id=msg.message_id)
```

Where generate_email is creating an EmailMultiAlternatives object. This is failing in tests because msg.message_id isn't working in tests. Presumably this is because Django is switching the email backend out on tests so they don't actually get sent. Based off what I've seen in this packages tests I've tried:

```
@override_settings(EMAIL_BACKEND='anymail.backends.test.TestBackend', ANYMAIL_TEST_SAMPLE_SETTING='sample',)
```

But that doesn't seem to be helping at all, also I have no idea what ANYMAIL_TEST_SAMPLE_SETTING is doing so 'sample' might be wrong. I can't seem to find anything in the docs covering what to do in this situation. Happy to write it up into the docs once I've got it working as it might be useful for other people.

**Comment by martmatwarne** [comment]
I take it back about my tests failing that was just me being wrong as the code should have been:

```
msg = self.generate_email()
msg.send()

status = msg.anymail_status

email_sent = self.create_sent_object(email_id=status.message_id)
```

I'll do a pull request about adding to the docs though. Is the override_settings line above the correct way or should I be doing something else?

**Comment by medmunds** [comment]
Django does indeed substitute its own [special email backend during testing](https://docs.djangoproject.com/en/1.10/topics/testing/tools/#email-services), by default.

I had actually intended Anymail's TestBackend for testing Anymail itself, and hadn't been thinking about other apps trying to test their use of Anymail. (That's why the TestBackend isn't documented. And why it has that weird required TEST_SAMPLE_SETTING, which was part of testing setting overrides.)

But what you're trying to do makes perfect sense, and it would probably be good to clean up and document the TestBackend. You're using it correctly with @override_settings. The ANYMAIL_TEST_SAMPLE_SETTING has to be there (for now), but can be set to anything.

**Comment by medmunds** [comment]
FYI, I just committed a change that would let you run your tests with Django's normal testing backend. The one change you'd need to make is to create an AnymailMessage, rather than a EmailMultiAlternatives, in your generate_email function.

With this update, the AnymailMessage now initializes anymail_status immediately, so you won't get an AttributeError on a missing anymail_status if Django's test backend processes the message instead of Anymail. The status.message_id will be None in this case, but hopefully your create_sent_object function is already handling a missing message_id (since that can also occur in production if, say, your ESP has an error).

(I'd still like to clean up and document Anymail's TestBackend, and will leave this issue open to cover that enhancement. But hopefully this change makes using the TestBackend less necessary in the common case.)
