### ISSUE TITLE
Brevo `trace_clicks` and `trace_opens`

### ISSUE THREAD

**Issue by Zerotask** [anymail/django-anymail#377]
- Anymail version: 10.3
- ESP (Mailgun, SendGrid, etc.): Brevo
- Versions of Django, requests, python: 5.0.x

The [documentation](https://anymail.dev/en/stable/esps/#anymail-feature-support) says that Brevo does not support trace_clicks and trace_opens. Although when you create a new WebHook in Brevo, you can check those events:
![image](https://github.com/anymail/django-anymail/assets/20150243/f11495ea-a57e-4e30-8233-6e1bcee65ca6)

**Comment by medmunds** [comment]
The docs are correct: Anymail's `track_opens` and `track_clicks` features cannot currently be supported for Brevo, due to limitations in their API. This is explained in [Anymail's Brevo documentation page](https://anymail.dev/en/stable/esps/brevo/#limitations-and-quirks:~:text=No%20click%2Dtracking%20or%20open%2Dtracking%20options) under *Limitations and quirks:*

> <dl>
> <dt>No click-tracking or open-tracking options</dt>
> <dd>Brevo does not provide a way to control open or click tracking for individual messages. Anymail’s <a href="https://anymail.dev/en/stable/sending/anymail_additions/#anymail.message.AnymailMessage.track_clicks">track_clicks</a> and <a href="https://anymail.dev/en/stable/sending/anymail_additions/#anymail.message.AnymailMessage.track_opens">track_opens</a> settings are unsupported.</dd>
> </dl>

Note that Anymail *does* support Brevo's click and open tracking *event webhooks* (also [noted in Anymail's documentation](https://anymail.dev/en/stable/esps/brevo/#status-tracking-webhooks:~:text=opened%20(see%20note%20above)%2C%20clicked)).

**Comment by medmunds** [comment]
I can see how [that table](https://anymail.dev/en/stable/esps/#anymail-feature-support) in the docs could be misleading, so I'm going to add some notes to try to clarify.
