### ISSUE TITLE
Webhooks in mailgun backend only work with newest 2.7 pythons 

### ISSUE THREAD

**Issue by sebbacon** [anymail/django-anymail#41]
`hmac.compare_digest` is [new in 2.7.7](https://docs.python.org/2/library/hmac.html#hmac.compare_digest). Debian Wheezy, LTS supported until May 2018, is [currently at 2.7.3](https://packages.debian.org/search?keywords=python2.7&searchon=names&exact=1&suite=all&section=all).

As a consequence, trying to use Mailgun mailhooks on Wheezy fails.

I suppose the fix is [something like this](https://github.com/liris/websocket-client/commit/4d5bc1e4e3622265ef7dc54281c0f73bb4dd98d6), along perhaps with a deprecation notice or similar?

**Comment by medmunds** [comment]
Ah, thanks for the catch. This also affects Mandrill webhooks. Travis-CI is currently running Python 2.7.9 for Python 2.7 builds, so it doesn't catch this. 

BTW, even once this is fixed in Anymail, there are some good reasons to run a newer Python 2.7 build, at least for your Django app. (For example, there's likely an urllib3 [InsecurePlatformWarning](https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings) lurking in your logs, where the call to Mailgun's https API can't be verified with the 2.7.3 urllib.) I've used the [Deadsnakes PPA](https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes-python2.7) to upgrade Python 2.7 on older Ubuntu LTS builds; not sure what the equivalent is for Debian.

**Comment by sebbacon** [comment]
OK. FWIW I started looking at using `tox` + `pyenv` to support a matrix of minor versions in travis, but it all got a bit complicated and I ran out of time :)

Thanks for a great library BTW.
