### ISSUE TITLE
how to handle ESP connection trouble

### ISSUE THREAD

**Issue by patroqueeet** [anymail/django-anymail#55]
dear,

how do you recommend to handle a 
```
AnymailRequestsAPIError: Sending a message to USER@DOMAIN.ch from noreply@DOMAIN.com ESP API response 504: <html><body><h1>504 Gateway Time-out</h1> The server didn't respond in time. </body></html>
```

or does anymail provide a simple logic which will try for a few times?

**Comment by medmunds** [comment]
> ESP API response 504: ... Gateway Time-out

Every production deployment will eventually have to deal with connectivity issues -- it's just the nature of accessing APIs over the internet. Anymail doesn't have built-in logic to retry network errors, because Django doesn't have a built-in way to say "try this again in a few moments."

A few options:

* If your project is already using something for background task scheduling (like [celery](http://docs.celeryproject.org/en/latest/index.html) or [django-channels](https://channels.readthedocs.io/en/stable/index.html)), that's usually the best choice for handling Anymail sends. You would queue a task for every send, and wait to mark the task complete until the send succeeds.

* If not, then the Pinax [django-mailer](https://github.com/pinax/django-mailer) package is a simple way to queue and automatically retry failed sends. It uses your regular Django DB to maintain the queue.

This is a topic that really should be covered in the Anymail docs.
