### ISSUE TITLE
Email parser error message improvement

### ISSUE THREAD

**Issue by bradreardon** [anymail/django-anymail#57]
We came across some issues when getting Anymail set up with our project. Ended up figuring out that the issue was that we were setting `message.reply_to` to a string instead of a `list`.

Could be a minor improvement to either (1) automatically check if that variable is set to a string and automatically put it as a single-element list, or (2) throw a more helpful error message when any variable that should be a list of email addresses like `to, bcc, cc, reply_to` is the incorrect data type.

You can reproduce this by trying to send an email where `message.reply_to = "test@example.com"` instead of `message.reply_to = ["test@example.com"]`.

Minor little thing, but could prevent some issues in the future, since the resulting error message is pretty cryptic.

I realize this issue is pretty devoid of any specifics, so feel free to let me know if any more details would help.

**Comment by medmunds** [comment]
I was a little confused, because I seemed to remember that Django already has exactly that sort of warning. And in fact it does: [`TypeError('"reply_to" argument must be a list or tuple')`](https://github.com/django/django/blob/1.8.17/django/core/mail/message.py#L246-L247). But Django checks it in`EmailMessage.__init__`, so it only catches the problem if you give `reply_to` as a param when you create the EmailMessage -- not if you set the attribute later like in your example.

It'd probably be helpful for Anymail to repeat Django's "expects list of strings, not a bare string" tests at send time, to catch the case you describe. 

Even though it would be a nicer API, I'd rather not automatically convert a bare string to a list. Django core defines the behavior of those attributes, and if Anymail handled them differently it would complicate switching between EmailBackends.

(Note to self: also catch bare lazy strings in to/cc/cc/reply_to; Django's current tests are probably fooled by that case. And the resulting error probably ends up [even more cryptic](https://github.com/anymail/django-anymail/issues/34).)

**Comment by medmunds** [comment]
Added code to catch non-list reply_to.

Unfortunately, Django throws cryptic TypeErrors on non-list to, cc, and bcc before Anymail even gets a chance to look at them. If you see one of these TypeError messages from django.core.mail.EmailMessage.recipients(), that's your problem: "must be str, not list"; "can only concatenate list (not "str") to list"; "Can't convert 'list' object to str implicitly".
