### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by alexislg2** [anymail/django-anymail#61]
Hello,
I am using anymail with mailgun for a year now and it has always been working perfectly. But for 48 hours now, I receive many error logs like this:

> ERROR 2017-04-24 09:29:51,512 Error posting to https://api.mailgun.net/v3/example.com/messages:
> SSLError: bad handshake: SysCallError(-1, 'Unexpected EOF')
> Sending a message to XXX YYY <xxx.yyy@gmail.com> from AAA BBB <XXX@example.com>
> Traceback (most recent call last):
>   File "./common/utils.py", line 26, in run
>     msg.send()
>   File "/usr/local/lib/python2.7/dist-packages/django/core/mail/message.py", line 342, in send
>     return self.get_connection(fail_silently).send_messages([self])
>   File "/usr/local/lib/python2.7/dist-packages/anymail/backends/base.py", line 86, in send_messages
>     sent = self._send(message)
>   File "/usr/local/lib/python2.7/dist-packages/anymail/backends/base_requests.py", line 56, in _send
>     return super(AnymailRequestsBackend, self)._send(message)
>   File "/usr/local/lib/python2.7/dist-packages/anymail/backends/base.py", line 116, in _send
>     response = self.post_to_esp(payload, message)
>   File "/usr/local/lib/python2.7/dist-packages/anymail/backends/base_requests.py", line 76, in post_to_esp
>     raised_from=err, email_message=message, payload=payload)
> AnymailRequestsAPIError: Error posting to https://api.mailgun.net/v3/example.com/messages:
> SSLError: bad handshake: SysCallError(-1, 'Unexpected EOF')
> Sending a message to XXX YYY <xxx.yyy@gmail.com> from AAA BBB <XXX@example.com>
> ERROR 2017-04-24 10:37:58,929 Error posting to https://api.mailgun.net/v3/example.com/messages:
> SSLError: bad handshake: SysCallError(-1, 'Unexpected EOF')
> Sending a message toXXX YYY <xxx.yyy@gmail.com> from AAA BBB <XXX@example.com>
> Traceback (most recent call last):
>   File "./common/utils.py", line 26, in run
>     msg.send()
>   File "/usr/local/lib/python2.7/dist-packages/django/core/mail/message.py", line 342, in send
>     return self.get_connection(fail_silently).send_messages([self])
>   File "/usr/local/lib/python2.7/dist-packages/anymail/backends/base.py", line 86, in send_messages
>     sent = self._send(message)
>   File "/usr/local/lib/python2.7/dist-packages/anymail/backends/base_requests.py", line 56, in _send
>     return super(AnymailRequestsBackend, self)._send(message)
>   File "/usr/local/lib/python2.7/dist-packages/anymail/backends/base.py", line 116, in _send
>     response = self.post_to_esp(payload, message)
>   File "/usr/local/lib/python2.7/dist-packages/anymail/backends/base_requests.py", line 76, in post_to_esp
>     raised_from=err, email_message=message, payload=payload)
> AnymailRequestsAPIError: Error posting to https://api.mailgun.net/v3/example.com/messages:
> SSLError: bad handshake: SysCallError(-1, 'Unexpected EOF')
> Sending a message to XXX YYY <xxx.yyy@gmail.com> from AAA BBB <XXX@example.com>

It looks like a SSL issue but I really do not understand why. This happens with arround 50% of the mails I send. It seems random

**Comment by medmunds** [comment]
This is the [requests](https://github.com/kennethreitz/requests/) package reporting that it can't successfully set up a secure network connection from your machine to Mailgun. The relevant root error is `SSLError: bad handshake: SysCallError(-1, 'Unexpected EOF')` -- try searching the web for that and you'll find a variety of possibilities and troubleshooting suggestions.

Since this stopped working recently, what changed? Did you upgrade your OS, Python, OpenSSL, requests, django-anymail, or any other packages? Did your networking environment change? New firewall rules (from you or your hosting provider)? Are you connecting through a proxy that might have changed? Any other config changes?

If none of that leads you to a solution, then it would be really helpful to have more details about your environment: OS version, exact Python version, versions of Anymail, requests, and OpenSSL, how you're hosted and any unusual network config, etc.

**Comment by alexislg2** [comment]
Thank you for your help. It was indeed not an issue with this package. I found the reason: I am using `threading` to send emails. I disable the `enable-threads` setting in uwsgi by mistake. Therefore Django was unable to start the thread to send email.

Error log was not so clear and it is not so clear why some emails were sent and some were not but nevermind.
