### ISSUE TITLE
Missing or invalid basic auth in Anymail Mailgun webhook

### ISSUE THREAD

**Issue by pymarco** [anymail/django-anymail#69]
Thank you for maintaining Anymail, it is really great so far.

I am trying to receive a webhook from Mailgun but I get an error.

    "Missing or invalid basic auth in Anymail Mailgun webhook"

Anymail is configured correctly, and I have been sending email through Mailgun for about a week.

    ANYMAIL = {
        "MAILGUN_API_KEY": Env.value("MAILGUN_API_KEY"),
        "MAILGUN_SENDER_DOMAIN": Env.value("MAILGUN_SENDER_DOMAIN"),
        "WEBHOOK_AUTHORIZATION": Env.value("ANYMAIL_WEBHOOK_AUTHORIZATION"),
    }

Today I added the "WEBHOOK_AUTHORIZATION" setting. Currently I am testing this feature on our dev environment. Therefore, the Mailgun sender domain is my Mailgun sandbox domain.

I set the Mailgun "Unsubscribes" web hook to the url defined in the Anymail documentation.

    https://secret1:secret2@dev.mysite.com/anymail/mailgun/tracking/

And in my urls.py

    url(
        r'^anymail/',
        include('anymail.urls')
    ),

When I receive an email and click the unsubscribe link, a POST is made to my server, but I get the error listed above.

For what it's worth, I am hosting my site on Webfaction using Apache.

I found a nearly identical issue on Stackoverflow, but no answer provided. 
https://stackoverflow.com/questions/38620608/django-anymail-mailgun-webhook-no-http-authorization-in-meta

**Comment by pymarco** [comment]
I fixed by adding the following to my apache conf.

    WSGIPassAuthorization On

**Comment by medmunds** [comment]
Thanks for providing the solution! I'll add a note to the docs.

**Comment by looeee** [comment]
I have the same issue but I'm running on NGINX and I've been unable to find out what NGINX equivalent directive to WSGIPassAuthorization is. If anybody knows, it would be great to get that added to the docs as well.

**Comment by medmunds** [comment]
@looeee take a look at https://serverfault.com/a/511612. If that solves the problem for you, we can definitely include it in the docs.

**Comment by looeee** [comment]
@medmunds thanks for the response. I must have tried about a hundred variations on that solution by now though, and always get one of two errors - either I get a "Missing or invalid basic auth" or I get an NGINX 404 page (not my site's 404, just the basic NGINX page). 

In the case of the 404 page, my logs say: "./html/anymail/mailgun/tracking/index.html" is not found (2: No such file or directory)"

**Comment by medmunds** [comment]
@looeee that makes it sound like there might be some other issues in your nginx config. (E.g., an nginx 404 trying to load ./html/.../index.html makes it sound like your proxy_pass into Django isn't even being considered on that url. Are other Django pages loading correctly?)

Two suggestions:
* To debug nginx/Django config without Anymail or Mailgun in the way, temporarily create a Django view that just logs and/or returns an HttpResponse with `request.META['HTTP_AUTHORIZATION']`. You should be able to load that with something like https://foo:bar@yoursite.example.com/testview, and the logged auth header should be "Basic *base64-val*" when nginx is properly configured.
* Ask about your specific nginx config on serverfault. (I'm pretty much an nginx novice, and things like the interactions between server, location, try_files, and proxy directives always confuse me. You'll probably get more accurate info from nginx experts.)

**Comment by looeee** [comment]
@medmunds yes, all other pages are working. If I set up basic auth on any page it fails in this way though. 

[I asked about this on serverfault previously](https://serverfault.com/questions/917226/nginx-basic-auth-is-set-up-and-working-but-all-protected-pages-return-404/924061#924061), it didn't get much traction though.

Thanks for the `request.META` - that's a simpler way of testing than I've been using so far, however I'm still getting a 404 page anytime I set up basic auth. I'll post back here if I have any success.

**Comment by medmunds** [comment]
@looeee I left a couple of comments in serverfault. It looks like you're trying to have nginx enforce basic auth on your webhooks, in addition to the basic auth enforcement that's built into Anymail. Checking it twice doesn't hurt anything, but it may be needlessly complicated. (And you'll need to keep nginx's .htpasswd file synced up with your Anymail WEBHOOK_SECRET setting.)

Probably easier to continue the nginx discussion over in serverfault.

If you've got a use case for enforcing webhook auth in your web server *instead of* in Anymail, please open a new issue here. (I've got a note to myself to support that at some point, but didn't want to add the complexity without a specific need for it.)

**Comment by looeee** [comment]
@medmunds since I have a better understanding of what's going on now, I've posted a new question on serverfault: https://serverfault.com/questions/924930/nginx-reverse-proxy-for-gunicorn-trouble-passing-basic-auth-credentials-to-ser 

I've actually found a lot of related questions (sending on basic auth credentials while using nginx as a reverse proxy), and none of them seem to have an answer.  However, I have been able to pass on a basic string "test" as the HTTP_AUTHORIZATION header. So I'm thinking that a workaround would be to pass:

    "Basic base64encode(SECRET:SECRET)" 

as the  HTTP_AUTHORIZATION header. I've tested this a bit but anymail is not accepting it so far - do you have any idea what the correct format of this string would be?

**Comment by looeee** [comment]
OK, it turns out that Chome and Firefox now silently strip credentials from URLS of the forms `foo:bar@example.com` _unless_ there is actually basic auth set up on the page. 🤦‍♂️ 

Since I was testing by setting the credentials this way I fell into this trap. Testing with `https://httpstatus.io/` and setting the credentials explicitly, the HTTP_AUTHORIZATION header is passed along correctly. My final `nginx.conf.erb` location blocks look like this:


```
        location / {
            proxy_set_header Host $host;
            proxy_pass http://app_server;

        }

        location /anymail/mailgun/tracking/ {

            proxy_set_header Host $host;
            proxy_pass http://app_server;

            proxy_set_header Authorization $http_authorization;

        }
```

However, testing the Mailgun webhook now sends me to the NGINX default 301 redirect page... I guess I should count that as progress.

**Comment by medmunds** [comment]
Ah, didn't realize browsers had made that change on sending basic auth from the url. (I've edited my original comment to suggest using curl instead.)

Did you see my comments in your serverfault questions? I'm still surprised that you need *any* special config to pass the auth header through the proxy: nginx's [default is supposed to proxy all headers](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/#passing-request-headers) (except Host and Connection).

BTW, just noticed that you're using "WEBHOOK_AUTHORIZATION" rather than "WEBHOOK_SECRET" in your settings. What version of Anymail are you using? (WEBHOOK_AUTHORIZATION was deprecated in v1.4 and eliminated in v2.0.)

**Comment by looeee** [comment]
> BTW, just noticed that you're using "WEBHOOK_AUTHORIZATION" rather than "WEBHOOK_SECRET" 

That's the original poster, @pymarco. I'm using version 3.0.6 (latest version I think?) with "WEBHOOK_SECRET" setting. 

In any case, I've gotten past the basic auth problem and now have a weird 301 redirect problem 😅 
I'll see if I can figure out anything with that and open a new issue if not. 

Thanks for your help with this.

**Comment by looeee** [comment]
OK, so the 301 error was just that  I was testing the webhook against `/anymail/mailgun/tracking` which was being redirected to `/anymail/mailgun/tracking/`. No big deal... 

BUT... Now I'm straight back to the original "Missing or invalid basic auth in Anymail Mailgun webhook" error. Full circle... 

I've retested that basic auth params are being passed on the page `/authtest`, and my location settings in nginx.conf.erb for `/authtest` and `/anymail/mailgun/tracking` are identical, so the basic auth header must be getting passed along _if_ it is set. 

Sothe problem must be that it's not getting set by the mailgun webhook. 

I'm testing the webhooks on the page https://app.mailgun.com/app/webhooks, using the various legacy webhooks to test, and the format of my webhook is `https://SECRET:SECRET@mysite.com/anymail/mailgun/tracking/`. 

Could it be that the same thing is happening to this URL as when I tried to test `foo:bar@example.com` and found that the `foo:bar` was getting silently stripped? I.E it's no longer valid to supply credentials in this manner?

**Comment by medmunds** [comment]
Hmmm...

I just verified that Mailgun is sending the correct Authorization header when a webhook is set to `https://abcde:fghij@471b2574.ngrok.io/anymail/mailgun/tracking/`. (Using ngrok with a local Django dev server, so nginx isn't in the mix. Have tested both a real send and using the "Test webhook" box at the bottom of Mailgun's webhook settings—both work.)

<img width="560" alt="mailgun webhook ngrok" src="https://user-images.githubusercontent.com/639984/43681085-6f1f3a70-97fe-11e8-8a3d-6fd3d24dc4e3.png">

One other option, at least for testing purposes, is to omit the WEBHOOK_SECRET setting (or set it to an empty list `[]`), which disables Anymail's basic auth checking.

**Comment by looeee** [comment]
I didn't realise that you could omit WEBHOOK_SECRET. I'll use that as a workaround while I'm setting up the rest of the backend. Thank you! 😄
