### ISSUE TITLE
SendinBlue

### ISSUE THREAD

**Issue by sachiv** [anymail/django-anymail#84]
Please add support for [SendinBlue](https://www.sendinblue.com/).

Thanks!

**Comment by medmunds** [comment]
Anymail users: to vote for this feature, use GitHub's thumbs-up reaction on the top comment.

Looks like SendInBlue is a good candidate for Anymail:
* Has free tier (so we can debug implementation and run regular tests)
* Transactional send API—looks like v3 is preferred: [send](https://developers.sendinblue.com/v3.0/reference#sendtransacemail-1) and [sendtemplate](https://developers.sendinblue.com/v3.0/reference#sendtemplate)
* REST API with json payloads, or python [client lib](https://github.com/sendinblue/APIv3-python-library) ([pypi](https://pypi.python.org/pypi/sib-api-v3-sdk/1.1.4)) (which is auto-generated from their Swagger spec, so presumably will be kept updated)
* Webhooks (but can't find any docs on the payloads, just how to [install](https://developers.sendinblue.com/v3.0/reference#webhooks-6) them)

It doesn't look like SendInBlue offers inbound email handling.

**Comment by RignonNoel** [comment]
Some people work on this integration or it's open to new contribution ?

I really need a SendinBlue integration in the next couple of month and i'm open to work on it if the community is ready to help me on the review side.

I've seen this file to begin, i guess it's up to date : https://github.com/anymail/django-anymail/blob/master/ADDING_ESPS.md

**Comment by medmunds** [comment]
@RignonNoel I'm not aware of anyone working on this yet. A PR would be very welcome.

The ADDING_ESPS.md file is a good starting point. I put that together pretty quickly, so let me know if you have any questions. And a work-in-progress PR can be a good place to discuss specific code, whenever you're ready.

I'd recommend creating an Anymail Requests backend that calls SendInBlue's REST API directly (rather than trying to use their Python client library). Their API uses straightforward JSON payloads and responses, so some good examples to start from are the [Postmark backend](https://github.com/anymail/django-anymail/blob/master/anymail/backends/postmark.py) and the *unreleased* [Mailjet *v3.1* backend](https://github.com/anymail/django-anymail/blob/feature_mailjet_v3.1/anymail/backends/mailjet.py) (on the feature_mailjet_v3.1 branch).

**Comment by medmunds** [comment]
Status:
- [x] Backend
- [ ] Tracking webhooks
- [x] ~Inbound webhooks~ (n/a: SendinBlue doesn't support inbound)
